### ISSUE TITLE
Do you (still) personally use this?

### ISSUE THREAD

**Issue by ghost** [jasononeil/hvm#4]
Heyo, I just wanted to open an issue to ask about the status of this lib.  It certainly *could* fill a solid need, and I personally would benefit from a mature lib.  However, there's docker, and it might just be easier for me, a linux user, to go that route.

Just saying "hey there!" and "what's the status of this project?"

:smile:

**Comment by jasononeil** [comment]
Hey thanks for saying hi!

No I don't use this anymore - I better put a big notice up in the README.  If you want a non-docker version, David Peek has a tool with the same name (but made using BASH) that I used for a while: https://github.com/dpeek/hvm

Now I'm also using the Haxe docker fwiw :)
